---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karma
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: karma
      sourceRef:
        kind: HelmRepository
        name: wiremind
      interval: 12h
  releaseName: karma
  values:
    env:
    - name: ALERTMANAGER_URI
      value: http://vmalertmanager-victoria-metrics-k8s-stack:9093
